name: build

on: [push, pull_request]

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            fail-fast: false
            matrix:
                operating-system: ['ubuntu-16.04']
                php-versions: ['8.0', '7.4', '7.3', '7.2', '7.1', '7.0', '5.6', '5.5', '5.4', '5.3']

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, dom
                  ini-values: max_execution_time=0
                  coverage: xdebug

            - name: Setup PHP_VERSION env variable
              run: |
                echo PHP_VERSION=$(echo "<?php echo join('.', array_slice(explode('.', PHP_VERSION), 0, 2)); " | php) >> $GITHUB_ENV

            - name: Install dependencies
              run: |
                echo PHP_VERSION: ${{ env.PHP_VERSION }}
                if [[ "${{ env.PHP_VERSION }}" = 8.* ]]; then
                  composer require --no-update phpunit/phpunit:^8.0.0
                fi
                composer install
                if [[ "${{ env.PHP_VERSION }}" = 8.* ]]; then
                  # Remove return type annotation from setUp() and tearDown(), to allow test cases
                  # to be executed in phpunit 8.* versions
                  sed -i -- 's/protected function \(setUp\)(): void/protected function \1()/g' vendor/phpunit/phpunit/src/Framework/TestCase.php
                  sed -i -- 's/protected function \(tearDown\)(): void/protected function \1()/g' vendor/phpunit/phpunit/src/Framework/TestCase.php
                fi

            - name: Run tests
              run: |
                mkdir -p build/logs
                COMPOSER_PROCESS_TIMEOUT=0 composer test -- --coverage-clover build/logs/clover.xml

            - name: Upload coverage results to Coveralls
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                if [ -f "build/logs/clover.xml" ] && [ -f "vendor/bin/php-coveralls" ]; then
                  php vendor/bin/php-coveralls -v;
                fi
